### ISSUE TITLE
How do you actually upload the code for the function?

### ISSUE THREAD

**Issue by justinmchase** [gjlumsden/AzureFunctionsSlots#1]
I am learning ARM templates, and I can create the webapp and if I manually upload the code it will actually run the function but I am not sure what the right way to deploy the actual code to the function is? I have seen some git examples but I don't want to use git I want to just push up a zipfile or something similar. How are you publishing the code for your functions?

**Comment by gjlumsden** [comment]
If you don't want to use the Git method there are still loads of options. My preferred approach is to use Visual Studio Team Services and create a build and release pipeline. This will automate the deployment whenever you commit to your repository's master branch (or another branch if you configure it like that). [VSTS](https://www.visualstudio.com/team-services/) is free for up to 5 users, and includes loads of excellent benefits, including a 3 month free trial of Pluralsight and other online learning resources. It also supports external repos, such as Github.

You can also use MSDeploy/WAWSDeploy, Kudu or Visual Studio to publish to the function app. Details about the the options can be found in [this blog post](https://blog.kloud.com.au/2016/09/04/azure-functions-deployment-strategies/). Details about deploying from Visual Studio can be found [in the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#publish-to-azure)

**Comment by justinmchase** [comment]
My solution was to use the new [Zip Deploy](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file) api in kudu and automate it from gulp.
